import * as THREE from 'three';
import { buildEnemy, animateEnemy, disposeShared } from './enemy-model.js';
import { clamp, clamp01, damp, lerp, smoothstep, wrapAngle, TAU } from '../core/math.js';
import { v3 } from '../core/scratch.js';

const STATE = {
  IDLE: 'idle', PATROL: 'patrol', ALERT: 'alert', ADVANCE: 'advance',
  COVER: 'cover', PEEK: 'peek', FIRE: 'fire', RELOCATE: 'relocate',
  SUPPRESS: 'suppress', FLANK: 'flank', HURT: 'hurt', DEAD: 'dead',
};

const MAX_ALIVE = 12;

/**
 * Cover-based squad AI.
 *
 * Enemies do not stand in the open trading shots. They hold cover, peek on a
 * rhythm, break contact when suppressed, and use the world's cover graph to
 * flank. The graph is generated by the world system from actual geometry, so
 * they use the same cars and barriers the player does.
 */
export class AiSystem {
  constructor(ctx) {
    this.ctx = ctx;
    this.rng = ctx.rng.stream('ai');
    this.enemies = [];
    this.pool = [];
    this.kills = 0;
    this.alerted = false;
    this._hit = { enemy: null, point: new THREE.Vector3(), distance: 0, part: 'body' };
    this._v = new THREE.Vector3();
    this._d = new THREE.Vector3();
  }

  init() {
    this.render = this.ctx.get('render');
    this.phys = this.ctx.get('physics');
    this.world = this.ctx.get('world');
    this.materials = this.ctx.get('materials');
    this.player = this.ctx.get('player');
    this.fx = this.ctx.get('fx');

    this.group = new THREE.Group();
    this.group.name = 'enemies';
    this.render.scene.add(this.group);

    this.cover = this.world.coverPoints;
    this.nav = this.world.navNodes;

    for (const enc of this.world.encounters) this._spawnEncounter(enc);
  }

  prewarm() {
    this.render.renderer.compile(this.render.scene, this.render.camera);
  }

  /* ------------------------------ spawning ------------------------------ */

  _spawnEncounter(enc) {
    const rng = this.rng.stream(enc.tag);
    for (let i = 0; i < enc.count; i++) {
      if (this.enemies.filter((e) => e.state !== STATE.DEAD).length >= MAX_ALIVE) return;
      // Find a cover point inside the encounter radius and stand behind it.
      const candidates = this.cover.filter((c) =>
        Math.hypot(c.x - enc.x, c.z - enc.z) < enc.radius && c.quality > 0.4);
      let x, z;
      if (candidates.length) {
        const c = rng.pick(candidates);
        const a = rng.next() * TAU;
        x = c.x + Math.cos(a) * 1.1;
        z = c.z + Math.sin(a) * 1.1;
      } else {
        const a = rng.next() * TAU;
        x = enc.x + Math.cos(a) * rng.range(0, enc.radius);
        z = enc.z + Math.sin(a) * rng.range(0, enc.radius);
      }
      const y = this.world.groundAt(x, z);
      if (!this.phys.capsuleFree(x, y + 0.1, z, 0.36, 1.7)) continue;
      this.spawn(x, y, z, enc);
    }
  }

  spawn(x, y, z, enc) {
    const rng = this.rng;
    let e = this.pool.pop();
    if (!e) {
      const model = buildEnemy(this.materials, rng);
      e = { model };
      this.group.add(model.root);
    }
    e.model.root.visible = true;
    e.pos = e.pos || new THREE.Vector3();
    e.vel = e.vel || new THREE.Vector3();
    e.pos.set(x, y, z);
    e.vel.set(0, 0, 0);
    e.home = { x, z, radius: enc ? enc.radius : 12 };
    e.state = STATE.IDLE;
    e.stateT = rng.range(0, 2);
    e.yaw = rng.next() * TAU;
    e.aimYaw = e.yaw;
    e.headYaw = 0;
    e.headPitch = 0;
    e.speed = 0;
    e.gaitPhase = rng.next() * TAU;
    e.crouched = false;
    e.aiming = false;
    e.recoil = 0;
    e.health = 100;
    e.maxHealth = 100;
    e.alertLevel = 0;
    e.awareness = 0;
    e.target = null;
    e.coverPoint = null;
    e.path = null;
    e.pathIndex = 0;
    e.fireTimer = rng.range(0.2, 1.2);
    e.burst = 0;
    e.ammo = 30;
    e.reloadT = 0;
    e.suppression = 0;
    e.lastSeen = null;
    e.reactionT = 0;
    e.peekT = 0;
    e.exposed = 0;
    e.deathT = 0;
    e.accuracy = rng.range(0.55, 0.85);
    e.aggression = rng.range(0.35, 0.9);
    e.tag = enc ? enc.tag : 'free';
    e.interior = !!(enc && enc.tag.includes('interior'));
    this.enemies.push(e);
    return e;
  }

  /* ------------------------------ queries ------------------------------- */

  /** Ray vs enemy capsules. Returns the nearest hit closer than maxDist. */
  raycastEnemies(origin, dir, maxDist) {
    let best = null, bestT = maxDist;
    for (const e of this.enemies) {
      if (e.state === STATE.DEAD) continue;
      const top = e.crouched ? 1.2 : 1.78;
      const t = this._raySegment(origin, dir, e.pos, top, 0.32, bestT);
      if (t === null) continue;
      bestT = t;
      const py = origin.y + dir.y * t;
      const rel = py - e.pos.y;
      const headY = e.crouched ? 1.05 : 1.62;
      const part = rel > headY - 0.14 ? 'head' : (rel < (e.crouched ? 0.45 : 0.85) ? 'limb' : 'body');
      best = { enemy: e, distance: t, part, point: new THREE.Vector3().copy(origin).addScaledVector(dir, t) };
    }
    return best;
  }

  /** Ray vs vertical capsule; returns t or null. */
  _raySegment(o, d, base, height, radius, maxT) {
    // Solve in XZ for the infinite cylinder, then clamp to the segment.
    const ox = o.x - base.x, oz = o.z - base.z;
    const a = d.x * d.x + d.z * d.z;
    if (a < 1e-9) return null;
    const b = 2 * (ox * d.x + oz * d.z);
    const c = ox * ox + oz * oz - radius * radius;
    const disc = b * b - 4 * a * c;
    if (disc < 0) return null;
    const sq = Math.sqrt(disc);
    let t = (-b - sq) / (2 * a);
    if (t < 0) t = (-b + sq) / (2 * a);
    if (t < 0 || t > maxT) return null;
    const y = o.y + d.y * t - base.y;
    if (y < 0 || y > height) return null;
    return t;
  }

  canSee(e, target, eyeH = 1.55) {
    return this.phys.lineOfSight(
      e.pos.x, e.pos.y + (e.crouched ? 1.0 : eyeH), e.pos.z,
      target.x, target.y, target.z,
    );
  }

  damageEnemy(e, amount, dir, part) {
    if (e.state === STATE.DEAD) return false;
    e.health -= amount;
    e.suppression = Math.min(1.6, e.suppression + 0.5);
    e.alertLevel = 1;
    this.alerted = true;
    // Getting shot from an unseen angle makes them break cover and reposition.
    if (e.state === STATE.COVER || e.state === STATE.IDLE || e.state === STATE.PATROL) {
      e.state = STATE.RELOCATE;
      e.stateT = 0;
    }
    if (e.health <= 0) {
      this._kill(e, dir);
      return true;
    }
    return false;
  }

  _kill(e, dir) {
    e.state = STATE.DEAD;
    e.deathT = 0;
    e.aiming = false;
    e.deathDir = dir ? { x: dir.x, z: dir.z } : { x: 0, z: 1 };
    e.model.flash.visible = false;
    this.kills++;
    this.ctx.events.emit('ai:kill', { pos: e.pos.clone() });
  }

  get aliveCount() { return this.enemies.reduce((n, e) => n + (e.state !== STATE.DEAD ? 1 : 0), 0); }

  /* ------------------------------- update ------------------------------- */

  fixedUpdate(dt) {
    const p = this.player;
    const pEye = v3[14].set(p.pos.x, p.pos.y + p.eyeHeight, p.pos.z);

    for (let i = 0; i < this.enemies.length; i++) {
      const e = this.enemies[i];
      if (e.state === STATE.DEAD) { this._updateDead(e, dt); continue; }
      this._updateEnemy(e, dt, p, pEye);
    }

    // Respawn pressure: keep the district contested without flooding it.
    this._respawnT = (this._respawnT || 0) - dt;
    if (this._respawnT <= 0) {
      this._respawnT = 9;
      if (this.aliveCount < 7 && !p.dead) {
        const enc = this.rng.pick(this.world.encounters);
        const d = Math.hypot(enc.x - p.pos.x, enc.z - p.pos.z);
        if (d > 34) this._spawnEncounter({ ...enc, count: 2 });
      }
    }
  }

  _updateEnemy(e, dt, p, pEye) {
    e.stateT += dt;
    e.suppression = Math.max(0, e.suppression - dt * 0.55);
    e.recoil = Math.max(0, e.recoil - dt * 7);
    if (e.reloadT > 0) e.reloadT -= dt;

    const eyeY = e.pos.y + (e.crouched ? 1.02 : 1.55);
    const toP = this._v.set(p.pos.x - e.pos.x, (p.pos.y + p.eyeHeight * 0.6) - eyeY, p.pos.z - e.pos.z);
    const dist = toP.length();
    const canSee = !p.dead && dist < 130 && this.phys.lineOfSight(e.pos.x, eyeY, e.pos.z, pEye.x, pEye.y, pEye.z);

    // ---- perception ----
    const facing = Math.cos(wrapAngle(Math.atan2(-toP.x, -toP.z) - e.yaw));
    const fov = facing > 0.15 ? 1 : 0.25;
    if (canSee) {
      const gain = (1.9 * fov) * clamp01(1 - dist / 120) + (this.alerted ? 0.5 : 0);
      e.awareness = clamp01(e.awareness + gain * dt);
      e.lastSeen = { x: p.pos.x, y: p.pos.y, z: p.pos.z, t: 0 };
    } else {
      e.awareness = clamp01(e.awareness - dt * 0.22);
      if (e.lastSeen) e.lastSeen.t += dt;
    }
    if (e.awareness > 0.6 && e.alertLevel < 1) {
      e.alertLevel = 1;
      this.alerted = true;
      e.reactionT = this.rng.range(0.14, 0.38);
      this.ctx.events.emit('ai:spotted', { pos: e.pos.clone() });
    }
    if (e.reactionT > 0) e.reactionT -= dt;

    const engaged = e.alertLevel > 0 && (canSee || (e.lastSeen && e.lastSeen.t < 6));

    // ---- state machine ----
    switch (e.state) {
      case STATE.IDLE:
        e.aiming = false;
        if (e.stateT > 3 + this.rng.next() * 4) { this._pickPatrol(e); }
        if (engaged) this._enterCombat(e, p);
        break;

      case STATE.PATROL:
        e.aiming = false;
        if (this._followPath(e, dt, 1.5)) { e.state = STATE.IDLE; e.stateT = 0; }
        if (engaged) this._enterCombat(e, p);
        break;

      case STATE.ALERT:
        e.aiming = true;
        this._faceTarget(e, e.lastSeen || p.pos, dt, 5);
        if (e.stateT > 1.4) this._enterCombat(e, p);
        break;

      case STATE.COVER: {
        e.aiming = true;
        e.crouched = e.coverPoint ? (e.coverPoint.height - e.pos.y) < 1.35 : false;
        this._faceTarget(e, e.lastSeen || p.pos, dt, 6);
        this._followPath(e, dt, 3.1);
        // peek on a rhythm modulated by suppression and aggression
        const readiness = e.aggression * (1 - e.suppression * 0.7);
        if (e.stateT > lerp(2.4, 0.7, readiness) && e.reloadT <= 0 && e.ammo > 0) {
          e.state = STATE.PEEK; e.stateT = 0; e.peekT = this.rng.range(0.9, 2.1);
        }
        if (e.suppression > 1.1 && this.rng.bool(dt * 1.5)) { e.state = STATE.RELOCATE; e.stateT = 0; }
        if (!canSee && e.lastSeen && e.lastSeen.t > 4.5) { e.state = STATE.ADVANCE; e.stateT = 0; }
        break;
      }

      case STATE.PEEK:
        e.aiming = true;
        e.crouched = false;
        this._faceTarget(e, p.pos, dt, 8);
        this._tryFire(e, dt, p, pEye, canSee, dist);
        e.peekT -= dt;
        if (e.peekT <= 0 || e.ammo <= 0 || e.suppression > 1.2) {
          e.state = STATE.COVER; e.stateT = 0;
          if (e.ammo <= 0) { e.reloadT = 2.4; e.ammo = 30; }
        }
        break;

      case STATE.ADVANCE:
        e.aiming = true;
        this._faceTarget(e, e.lastSeen || p.pos, dt, 5);
        if (!e.path) this._pathToward(e, e.lastSeen ? e.lastSeen : p.pos, 14);
        if (this._followPath(e, dt, 3.4) || e.stateT > 7) {
          this._enterCombat(e, p);
        }
        if (canSee && dist < 42 && this.rng.bool(dt * 2.5)) this._enterCombat(e, p);
        this._tryFire(e, dt, p, pEye, canSee && dist < 45, dist);
        break;

      case STATE.RELOCATE: {
        e.aiming = true;
        e.crouched = false;
        if (!e.path) {
          const c = this._findCover(e, p, 22, e.coverPoint);
          if (c) { e.coverPoint = c; this._pathToward(e, { x: c.x, z: c.z }, 30); }
          else { e.state = STATE.COVER; e.stateT = 0; break; }
        }
        this._faceMotion(e, dt);
        if (this._followPath(e, dt, 4.6) || e.stateT > 6) { e.state = STATE.COVER; e.stateT = 0; }
        break;
      }

      case STATE.FLANK: {
        e.aiming = true;
        if (!e.path) {
          const c = this._findFlank(e, p);
          if (c) { e.coverPoint = c; this._pathToward(e, { x: c.x, z: c.z }, 45); }
          else { e.state = STATE.COVER; e.stateT = 0; break; }
        }
        this._faceMotion(e, dt);
        if (this._followPath(e, dt, 4.2) || e.stateT > 11) { e.state = STATE.COVER; e.stateT = 0; }
        break;
      }
    }

    // ---- movement integration ----
    const targetSpeed = e.path ? e.moveSpeed || 0 : 0;
    e.speed = damp(e.speed, targetSpeed, 8, dt);

    // gravity + ground snap
    e.pos.y = this.world.groundAt(e.pos.x, e.pos.z);

    // ---- transform ----
    const m = e.model;
    m.root.position.copy(e.pos);
    m.root.rotation.y = e.yaw;
    // head look
    const dyaw = wrapAngle(Math.atan2(-toP.x, -toP.z) - e.yaw);
    e.headYaw = clamp(dyaw, -1.1, 1.1) * (e.alertLevel > 0 ? 1 : 0.3);
    e.headPitch = clamp(-Math.atan2(toP.y, Math.hypot(toP.x, toP.z)), -0.5, 0.5) * (e.alertLevel > 0 ? 1 : 0.2);
  }

  _enterCombat(e, p) {
    const c = this._findCover(e, p, 18, null);
    if (c) {
      e.coverPoint = c;
      this._pathToward(e, { x: c.x, z: c.z }, 26);
      e.state = STATE.COVER;
    } else {
      e.state = STATE.ADVANCE;
      e.path = null;
    }
    e.stateT = 0;
    // Occasionally one member of the squad breaks wide instead.
    if (this.rng.bool(0.22 * e.aggression)) { e.state = STATE.FLANK; e.path = null; }
  }

  /* ------------------------------ shooting ------------------------------ */

  _tryFire(e, dt, p, pEye, canSee, dist) {
    if (!canSee || e.reloadT > 0 || e.reactionT > 0 || p.dead) return;
    e.fireTimer -= dt;
    if (e.fireTimer > 0) return;

    if (e.burst <= 0) {
      e.burst = this.rng.int(3, 6);
      e.fireTimer = 0.09;
      return;
    }

    e.burst--;
    e.ammo--;
    e.fireTimer = e.burst > 0 ? 0.095 : this.rng.range(0.55, 1.4) * (2 - e.aggression);
    e.recoil = 1;
    e.model.flash.visible = true;
    e.model.flash.scale.setScalar(this.rng.range(0.7, 1.3));
    e._flashT = 0.04;

    // Accuracy degrades with range, player movement and their own suppression.
    const moveFactor = 1 + Math.hypot(p.vel.x, p.vel.z) * 0.09;
    const spread = lerp(0.012, 0.075, clamp01(dist / 90))
      * moveFactor * (2 - e.accuracy) * (1 + e.suppression * 0.9);
    const a = this.rng.next() * TAU;
    const r = Math.sqrt(this.rng.next()) * spread;

    e.model.muzzle.getWorldPosition(this._v);
    const dir = this._d.set(pEye.x - this._v.x, pEye.y - 0.15 - this._v.y, pEye.z - this._v.z).normalize();
    dir.x += Math.cos(a) * r; dir.y += Math.sin(a) * r * 0.7; dir.z += Math.sin(a) * r;
    dir.normalize();

    const hit = this.phys.raycast(this._v.x, this._v.y, this._v.z, dir.x, dir.y, dir.z, 140, 2);
    // Does the shot reach the player before it hits geometry?
    const toPlayer = Math.hypot(pEye.x - this._v.x, pEye.y - this._v.y, pEye.z - this._v.z);
    const blocked = hit.hit && hit.distance < toPlayer - 0.4;

    // Miss distance at the player's plane, for the crack-and-thump cue.
    const px = this._v.x + dir.x * toPlayer;
    const py = this._v.y + dir.y * toPlayer;
    const pz = this._v.z + dir.z * toPlayer;
    const miss = Math.hypot(px - pEye.x, py - pEye.y, pz - pEye.z);

    if (!blocked && miss < 0.45) {
      const dmg = lerp(15, 7, clamp01(dist / 80));
      p.damage(dmg, e.pos);
    } else {
      if (!blocked && miss < 3.2) this.ctx.events.emit('ai:nearMiss', { dist: miss });
      if (hit.hit) this.fx.surfaceImpact(hit.point, hit.normal, hit.surface, dir);
    }
    this.fx.tracer(this._v, hit.hit ? hit.point : { x: px, y: py, z: pz }, 700);
    this.fx.muzzleSmoke(this._v, dir);
    this.ctx.events.emit('ai:fire', { pos: e.pos.clone(), dist });
  }

  /* ------------------------------ navigation ---------------------------- */

  _nearestNode(x, z) {
    let best = -1, bd = Infinity;
    const n = this.nav;
    for (let i = 0; i < n.length; i++) {
      const d = (n[i].x - x) * (n[i].x - x) + (n[i].z - z) * (n[i].z - z);
      if (d < bd) { bd = d; best = i; }
    }
    return best;
  }

  /** Breadth-first path over the nav graph, capped so it never stalls a frame. */
  _pathToward(e, target, maxNodes = 30) {
    const start = this._nearestNode(e.pos.x, e.pos.z);
    const goal = this._nearestNode(target.x, target.z);
    if (start < 0 || goal < 0) { e.path = null; return false; }
    if (start === goal) {
      e.path = [{ x: target.x, z: target.z }];
      e.pathIndex = 0;
      e.moveSpeed = 3;
      return true;
    }
    const n = this.nav;
    const prev = new Int32Array(n.length).fill(-1);
    const seen = new Uint8Array(n.length);
    const queue = [start];
    seen[start] = 1;
    let head = 0, visited = 0, found = false;
    while (head < queue.length && visited < maxNodes * 12) {
      const cur = queue[head++];
      visited++;
      if (cur === goal) { found = true; break; }
      const links = n[cur].links;
      for (let i = 0; i < links.length; i++) {
        const nx = links[i];
        if (seen[nx]) continue;
        seen[nx] = 1;
        prev[nx] = cur;
        queue.push(nx);
      }
    }
    if (!found) { e.path = null; return false; }
    const path = [];
    let cur = goal;
    while (cur !== -1 && path.length < 120) {
      path.push({ x: n[cur].x, z: n[cur].z });
      if (cur === start) break;
      cur = prev[cur];
    }
    path.reverse();
    path.push({ x: target.x, z: target.z });
    e.path = path;
    e.pathIndex = 0;
    return true;
  }

  _pickPatrol(e) {
    const a = this.rng.next() * TAU;
    const r = this.rng.range(4, e.home.radius);
    this._pathToward(e, { x: e.home.x + Math.cos(a) * r, z: e.home.z + Math.sin(a) * r }, 18);
    e.moveSpeed = 1.5;
    e.state = STATE.PATROL;
    e.stateT = 0;
  }

  /** Steer along the current path. Returns true when finished. */
  _followPath(e, dt, speed) {
    if (!e.path) return true;
    e.moveSpeed = speed;
    const wp = e.path[e.pathIndex];
    if (!wp) { e.path = null; return true; }
    let dx = wp.x - e.pos.x, dz = wp.z - e.pos.z;
    const d = Math.hypot(dx, dz);
    if (d < 0.85) {
      e.pathIndex++;
      if (e.pathIndex >= e.path.length) { e.path = null; e.speed = 0; return true; }
      return false;
    }
    dx /= d; dz /= d;
    const step = speed * dt;
    const nx = e.pos.x + dx * step;
    const nz = e.pos.z + dz * step;
    if (this.phys.capsuleFree(nx, e.pos.y + 0.15, nz, 0.34, e.crouched ? 1.2 : 1.75)) {
      e.pos.x = nx; e.pos.z = nz;
    } else {
      // slide along the obstruction rather than sticking to it
      if (this.phys.capsuleFree(e.pos.x + dx * step, e.pos.y + 0.15, e.pos.z, 0.34, 1.75)) e.pos.x += dx * step;
      else if (this.phys.capsuleFree(e.pos.x, e.pos.y + 0.15, e.pos.z + dz * step, 0.34, 1.75)) e.pos.z += dz * step;
      else { e.pathIndex++; if (e.pathIndex >= e.path.length) { e.path = null; return true; } }
    }
    return false;
  }

  _faceTarget(e, t, dt, rate) {
    const want = Math.atan2(-(t.x - e.pos.x), -(t.z - e.pos.z));
    e.yaw += wrapAngle(want - e.yaw) * clamp01(rate * dt);
  }

  _faceMotion(e, dt) {
    if (!e.path) return;
    const wp = e.path[e.pathIndex];
    if (!wp) return;
    this._faceTarget(e, wp, dt, 7);
  }

  /* -------------------------------- cover ------------------------------- */

  /** Cover that breaks line of sight to the player but keeps them reachable. */
  _findCover(e, p, maxDist, exclude) {
    let best = null, bestScore = -Infinity;
    const px = p.pos.x, pz = p.pos.z;
    for (let i = 0; i < this.cover.length; i++) {
      const c = this.cover[i];
      if (c === exclude) continue;
      const d = Math.hypot(c.x - e.pos.x, c.z - e.pos.z);
      if (d > maxDist) continue;
      const dp = Math.hypot(c.x - px, c.z - pz);
      if (dp < 6) continue;                       // never take cover in their lap
      if (c.interior !== !!e.interior && dp > 40) continue;

      // Stand on the far side of the cover from the player.
      const ox = c.x - px, oz = c.z - pz;
      const on = Math.hypot(ox, oz) || 1;
      const sx = c.x + (ox / on) * 0.95;
      const sz = c.z + (oz / on) * 0.95;
      if (!this.phys.capsuleFree(sx, this.world.groundAt(sx, sz) + 0.1, sz, 0.34, 1.7)) continue;

      // Prefer: good cover, mid-range to the player, not far to walk.
      const rangeScore = 1 - Math.abs(dp - 26) / 40;
      const score = c.quality * 2.4 + rangeScore * 1.6 - d * 0.045 + this.rng.next() * 0.5;
      if (score > bestScore) {
        bestScore = score;
        best = { ...c, x: sx, z: sz, height: c.height };
      }
    }
    return best;
  }

  _findFlank(e, p) {
    const px = p.pos.x, pz = p.pos.z;
    const side = this.rng.bool() ? 1 : -1;
    const ang = Math.atan2(e.pos.z - pz, e.pos.x - px) + side * this.rng.range(0.9, 1.9);
    const r = this.rng.range(18, 34);
    const tx = px + Math.cos(ang) * r;
    const tz = pz + Math.sin(ang) * r;
    let best = null, bd = Infinity;
    for (const c of this.cover) {
      const d = Math.hypot(c.x - tx, c.z - tz);
      if (d < bd && c.quality > 0.5) { bd = d; best = c; }
    }
    return bd < 16 ? best : null;
  }

  /* -------------------------------- death ------------------------------- */

  _updateDead(e, dt) {
    e.deathT += dt;
    const m = e.model;
    const t = clamp01(e.deathT / 0.9);
    // ragdoll-lite: collapse the hips, fold the legs, rotate onto the back
    m.hips.position.y = lerp(0.92, 0.24, smoothstep(0, 1, t));
    m.root.rotation.x = lerp(0, -1.35 * Math.sign(e.deathDir.z || 1), smoothstep(0.1, 1, t));
    m.root.rotation.z = lerp(0, 0.35 * (e.deathDir.x > 0 ? 1 : -1), smoothstep(0.1, 1, t));
    m.hips.rotation.x = lerp(0.06, 0.5, t);
    for (const l of m.legs) {
      l.hip.rotation.x = lerp(l.hip.rotation.x, -0.5, 1 - Math.exp(-6 * dt));
      l.knee.rotation.x = lerp(l.knee.rotation.x, 1.1, 1 - Math.exp(-6 * dt));
    }
    for (const a of m.arms) {
      a.shoulder.rotation.x = lerp(a.shoulder.rotation.x, 0.4, 1 - Math.exp(-5 * dt));
      a.elbow.rotation.x = lerp(a.elbow.rotation.x, -0.2, 1 - Math.exp(-5 * dt));
    }
    if (e.deathT > 22) {
      m.root.visible = false;
      const i = this.enemies.indexOf(e);
      if (i >= 0) this.enemies.splice(i, 1);
      this.pool.push(e);
    }
  }

  update(dt) {
    for (const e of this.enemies) {
      if (e._flashT > 0) {
        e._flashT -= dt;
        if (e._flashT <= 0) e.model.flash.visible = false;
      }
      if (e.state === STATE.DEAD) continue;
      animateEnemy(e.model, e, dt);
    }
  }

  dispose() {
    disposeShared();
    this.group.removeFromParent();
  }
}

export { STATE };
